---
apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "app"
  namespace: "default"
spec:
  backend:
    serviceName: "app"
    servicePort: 80
  rules:
  - http:
      paths:
      - path: "/"
        backend:
          serviceName: "app"
          servicePort: 80